[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = {path = "../types"}
uefi = { version = "0.12" }
x86_64 = "0.14"
lazy_static = {version = "1.4", features = ["spin_no_std"]}
spin = "0.9"
# bitflags = "1.3"
bit_field = "0.10"
pic8259 = "0.10"
conquer-once = {version = "0.3", default-features = false}
# linked_list_allocator = "0.9.0"
crossbeam-queue = {version = "0.2", default-features = false, features = ["alloc"]}
linked_list_allocator = "0.9.0"

acpi = "4.1"