[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = {path = "../bootloader"}
kernel_userspace = {path = "../kernel_userspace"}
input = {path = "../input"}
uefi = "0.19"

x86_64 = "0.14"
lazy_static = {version = "1.4", features = ["spin_no_std"]}
spin = "0.9"
bit_field = "0.10"
conquer-once = {version = "0.4", default-features = false}
crossbeam-queue = {version = "0.3", default-features = false, features = ["alloc"]}
linked_list_allocator = "0.9.0"
acpi = "4.1"
modular-bitfield = { version = "0.11", default-features = false}

volatile = "0.3"

[profile.dev]
# Increase speed by 1000% since there are lots of hot loops / "zero cost" abstrations that need optimising
opt-level = 1